### PR TITLE
Fix test commands for pulp-certguard

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by ggainey** [comment]
I did a quick test w/ this PR in place, and I still can't test pulp-certguard:
```
(oci-env) (pull-request-mdellweg-fix_test_commands) ~/github/Pulp3/oci_env $ oci-env test -p pulp-certguard functional 
pytest is /usr/local/bin/pytest
========================================================= test session starts =========================================================
platform linux -- Python 3.8.13, pytest-7.2.2, pluggy-1.0.0
rootdir: /var/lib/pulp
plugins: pulpcore-3.23.1.dev0, xdist-3.2.1, custom-exit-code-0.3.0, pulp-smash-1!0.13.0
collected 0 items                                                                                                                     

======================================================== no tests ran in 0.00s ========================================================
ERROR: module or package not found: pulp_certguard.tests.functional (missing __init__.py?)
```

**Comment by mdellweg** [comment]
Did you rebuild the container images to get the modified scripts into place?

**Comment by ggainey** [comment]
> Did you rebuild the container images to get the modified scripts into place?

Hm - I thought I had, but I will retry making sure to start with a completely clean slate.

**Comment by ggainey** [comment]
> Hm - I thought I had, but I will retry making sure to start with a completely clean slate.

PEBKAC found and fixed, working now.

**Pull request merged**
