### PR TITLE
Add rpm plugin profile

### PR DESCRIPTION
**Pull request by dralley**
[noissue]

### CODE REVIEW

**Review by newswangerd — APPROVED** [review]

**Comment by dralley** [comment]
Is this a known test failure?

**Comment by newswangerd** [comment]
I think so. We've finally got most of the issues caused by the change in the base images fixed.

**Comment by dralley** [comment]
I don't have permissions to do anything with the CI, but it seems like it's stuck since it has been running for hours now.

**Comment by bmbouter** [comment]
@dralley what does the rpm plugin profile provide?

**Comment by dralley** [comment]
The main thing is I have no idea why the CI is failing.  I've seen the error before with the container before when I don't reset the database before bringing everything up so maybe something similar is going on.

**Review by bmbouter — APPROVED** [review]

**Pull request merged**
