### PR TITLE
Add correct logic for new templated nginx file

### PR DESCRIPTION
**Pull request by gerrod3**
Based on this new feature being added to the ci-centos image: https://github.com/pulp/pulp-oci-images/pull/623

### CODE REVIEW

**Comment by jctanner** [comment]
@gerrod3 galaxy's oci setups are broken without this patch ... do you plan to take it out of WIP soon and merge?

**Comment by mdellweg** [comment]
@jctanner can you unblock galaxy by selecting a known to work base image tag?

**Comment by jctanner** [comment]
@mdellweg yes, but as soon as this PR is merged, we'll have to change it again.

https://github.com/ansible/galaxy_ng/pull/2116

**Comment by mdellweg** [comment]
> @mdellweg yes, but as soon as this PR is merged, we'll have to change it again.
> 
> [ansible/galaxy_ng#2116](https://github.com/ansible/galaxy_ng/pull/2116)

Sure, it's only a stop gap. But I basically wanted to know if we are in the position to workaround such environmental dependencies. Great to hear we are.

**Review by jctanner — APPROVED** [review]

**Pull request merged**
