### PR TITLE
Add pulp-cli-deb to dev requirements

### PR DESCRIPTION
**Pull request by quba42**
[noissue]

### CODE REVIEW

**Review by mdellweg — COMMENTED** [review]
Want to add ostree too?

**Comment by lubosmj** [comment]
What are the benefits of doing this? Will I be able to develop cli stuff without installing it manually inside the container with pip install -e?

**Comment by quba42** [comment]
@lubosmj The following set of CLI commands will be available out of the box:
```
oci-env pulp deb --help
oci-env pulp ostree --help
```
Just like how `oci-env pulp file --help` is already available. This makes it easier to work on those plugins. If you want to work on the CLI itself, I think it makes the most sense to configure a CLI running entirely outside of the containers to point at your oci_env pulp instance, but that may be personal preference.

However, looking at the tests it looks like pulp-cli-ostree is currently breaking all of pulp-cli...

**Comment by quba42** [comment]
@mdellweg It looks like the CI failure due to some incompatibility in `pulp-cli-ostree` is consistent. When I build the image locally I do not run into this issue and using `pulp-cli-ostree` works just fine. Not sure how to explain the discrepancy.

**Comment by lubosmj** [comment]
@quba42, let's remove the ostree dependency for now. We will revisit it later.

**Comment by mdellweg** [comment]
@lubosmj This will install a released version. Not the source with `-e`. It is focused on use, not on development.

**Review by lubosmj — APPROVED** [review]

**Pull request merged**
