### PR TITLE
S6 upgrade fixes

### PR DESCRIPTION
**Pull request by newswangerd**
Fixes required to work with the S6 V3 upgrade to pulp-oci-images:
- https://github.com/pulp/pulp-oci-images/pull/231

### CODE REVIEW

**Comment by bmbouter** [comment]
I'm testing this.

**Review by dkliban — APPROVED** [review]

**Comment by bmbouter** [comment]
On `main` I currently get this error:

```
6b665930d2ea s6-supervise nginx (child): fatal: unable to exec run: Permission denied
6b665930d2ea s6-supervise nginx: warning: unable to spawn ./run - waiting 10 seconds
6b665930d2ea s6-supervise pulpcore-content (child): fatal: unable to exec run: Permission denied
6b665930d2ea s6-supervise pulpcore-content: warning: unable to spawn ./run - waiting 10 seconds
6b665930d2ea s6-supervise redis (child): fatal: unable to exec run: Permission denied
6b665930d2ea s6-supervise redis: warning: unable to spawn ./run - waiting 10 seconds
6b665930d2ea s6-supervise postgresql (child): fatal: unable to exec run: Permission denied
6b665930d2ea s6-supervise postgresql: warning: unable to spawn ./run - waiting 10 seconds
```

That's the right error right?

**Review by bmbouter — APPROVED** [review]
After applying this PR my environment is working (with the latest pulp-oci-images)

**Comment by bmbouter** [comment]
@newswangerd it needs CI fixes though

**Comment by bmbouter** [comment]
wrong button whoops...

**Comment by newswangerd** [comment]
@bmbouter good news, I made the reset db command faster and you don't have to run `compose logs -f` to get your console back

**Comment by bmbouter** [comment]
Thank you for this!

**Pull request merged**
